### ISSUE TITLE
[1.6.0 b4] Export Samples just freezes machine

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerBetaTesting#1512] opened 2022-05-13 15:33 UTC
steps to reproduce 👍 
Open project
Go to File : export samples
all controls unresponsive. Screen remains as is (indefinitely)
cancel has no effect
Unit freezes requiring hard reboot

**Comment by Synthdawg** [comment] 2022-05-13 15:36
Reported already as #1478

**Comment by bambrose** [comment] 2022-05-13 16:18
Sorry

**Comment by Synthdawg** [comment] 2022-05-14 12:53
Haha no prob, better to report twice than not at all I would say.

**Comment by Jacknametrouble** [comment] 2022-05-16 09:31
Duplicate of #1487

**Closed by Jacknametrouble** 2022-05-16 09:31 UTC
Labels: bug

**Comment by Jacknametrouble** [comment] 2022-05-19 18:27
Fixed in 1.6.0b5
