### ISSUE TITLE
1.6.0 beta 1 - Can't change CCs on MIDI instruments

### ISSUE THREAD

**Issue by cooptrol** [polyend/TrackerBetaTesting#1450] opened 2022-03-31 20:26 UTC
Restarted, loaded different projects, I cant modify the CCs assigned to ABCDEF, nor with the jogwheel nor with the arrows. If I press Delete the CC resets to 1 ModWh, and still can't be changed. 

* Does this bug happen in previous firmware versions? NO

* Does this bug happen in every project? YES

**Comment by Jacknametrouble** [comment] 2022-03-31 20:48
Duplicate of #1433

**Closed by Jacknametrouble** 2022-03-31 20:48 UTC
Labels: bug
