### ISSUE TITLE
[1.4.1b1] Sample recorder won't record if MIDI chord is playing

### ISSUE THREAD

**Issue by depaffect** [polyend/TrackerBetaTesting#1326] opened 2021-12-18 01:32 UTC
### Steps to reproduce

Just for background, I've edited the title and body of this bug report as I've narrowed the issue much further. And thankfully, it turns out it's much less of an issue - but worth reporting I think. 

The background is : I was having problems sample recording my synth being sequenced by a pattern that used MIDI Chord FX - when I removed the Chord FX, the problem disappeared. 

However it turns out the issue I had (sample recorder stops recording) is because there were some steps that had no notes, but still had the Chord FX. This seems to confuse the Tracker.

SO : If you have the MIDI chord FX on a step that has no notes on it; sample recorder will "pause" recording as soon as it hits that MIDI Chord FX. And if you stop playback of the pattern, recording will resume.

Even if you're not recording; you can see the level meter freeze on the monitoring screen if that pattern is playing.

This happens regardless of the source you're actually recording.

### Attachments and links

Youtube video to show problem : https://www.youtube.com/watch?v=40iPmT8RPDc

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")
Every time and I confirmed another user can reproduce this problem.

* Does this bug happen in previous firmware versions?
Unsure!

* Does this bug happen in every project?
Yes

**Comment by egoshiner** [comment] 2021-12-29 05:38
I thought this was intentional due to the live nature of playing chords on a more advanced synth/the irreplicatable aspects of modular. Tonight, I rendered stems/a pattern which was mainly composed of my TTSH Arp 26 being played using both the MIDI Ch Instrument, as well as trying the MIDI Chord effect. In the render, there is zero sound from the stereo Line-in and I just hear onboard samples, even isolating the individual track triggering the MIDI device.

From my perspective, this is more of an inadvertent feature-turned bug as it makes sense to rely on hard-set tracked samples being played with almost no generative aspect outside of the randomness they can permutate using. 

However, not even being able to step aside and record, because the MIDI Chord is playing, sounds too wrong.

**Comment by MortalJS** [comment] 2021-12-30 13:12
Bug confirmed.
@ziej8asek

**Comment by Jacknametrouble** [comment] 2022-01-15 21:12
Fixed in v1.5.0

**Closed by Jacknametrouble** 2022-01-15 21:12 UTC
Labels: bug, bug confirmed, fixed
