### ISSUE TITLE
[1.4.0] Upgrade to 1.4.0 fails

### ISSUE THREAD

**Issue by colonel-blimp** [polyend/TrackerBetaTesting#1321] opened 2021-12-15 01:09 UTC
I got a new Tracker with 1.3.1 firmware, but couldn't upgrade to the latest 1.4.0 firmware I downloaded from https://polyend.com/downloads/.  No matter what I tried, the update always failed immediately after starting.

However, I was able to update to 1.4.1-beta1 without any problems, so now I'm using that.

### Steps to reproduce

1. Download and extract 1.4.0 firmware
2. Apply update
3. Within a few seconds, Upgrade screen/Polyend Tool reports that the Update failed

#### Variations I tried

I tried a few different things to apply the 1.4.0 firmware, including:

Downloading:
  * using different browsers Firefox, Chrome
  * using different OSes: Windows, iOS

Extracting
  * Used OS native extraction 
  * Also used 7zip (Windows)

Applying
  * Approach 1: Used SD card + upgrade from Config menu
  * Approach 2: Took out SD card, entered emergency flashing mode, upgraded with Polyend Tool

### Attachments and links

[Polyend_Tracker_Firmware_v1.4.0.zip](https://github.com/polyend/TrackerIssues/files/7715714/Polyend_Tracker_Firmware_v1.4.0.zip)

### Other important information

* How often does this bug happen? (every time, often, "it only happened once")

  The failure happened every time I tried to upgrade to 1.4.0

   However: I can upgrade back and forth between 1.3.1 and 1.4.1-beta1 without any problems

* Does this bug happen in previous firmware versions?

   The upgrade to 1.4.0 failed from both 1.3.1 and from 1.4.1-beta1

**Comment by MortalJS** [comment] 2021-12-30 12:06
Hi @colonel-blimp 

Unfortunately I am unable to reproduce this error. I have not had a single problem of this type since I have been working with Tracker.

I am therefore closing the topic.

**Closed by MortalJS** 2021-12-30 12:06 UTC
Labels: bug, cannot reproduce
