### ISSUE TITLE
[1.3.0] SD Card (Tracker) no longer mounts via android file transfer

### ISSUE THREAD

**Issue by bambrose** [polyend/TrackerBetaTesting#574] opened 2020-12-24 12:02 UTC
On all previous versions I could use Android File Transfer to access contents of SD card via the 'file transfer' item in the config menu.
This has stopped working on most recent beta (i.e. I am having to remove SD card and use USB reader provided)
I'm on MacOSX 10.10.5 if that matters.. just weird to me that it's stopped working

**Comment by Just-Peter** [comment] 2020-12-24 14:10
I can confirm that Android File Transfer to access contents of SD card via the 'file transfer' is not working anymore. In 1.3.0b5 it was still working. I'm using a Mac Mini M1 with Big Sur 1.11

**Comment by jaap3** [comment] 2020-12-24 14:13
I've was able to get Android File Transfer to access the Tracker on MacOS 10.14.6, but transferring a (tiny) file doesn't work. Afterwards AFT stops seeing the Tracker and closes itself. Restarting File Transfer Mode a couple of time seems to make the Tracker available, but copying a file still doesn't work.

**Comment by piotr3500** [comment] 2020-12-24 14:57
I'm testing on osx via Command One program and it works fine.

**Comment by Just-Peter** [comment] 2020-12-24 15:36
That’s good to hear! But why doesn’t work Android File Transfer on the Mac anymore? It was working on 1.3.0b5, but not on 1.3.0. final. From: piotr3500Sent: Thursday, 24 December 2020 15:57To: polyend/TrackerIssuesCc: Just-Peter; CommentSubject: Re: [polyend/TrackerIssues] [1.3.0] SD Card (Tracker) no longer mounts via android file transfer (#574) I'm testing on osx via Command One program and it works fine.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Just-Peter** [comment] 2020-12-24 21:59
@piotr3500 I don't see any MTP devices in Commander One when I choose 'start file transfer' on my Tracker. How did you do this?

**Comment by ndguardian** [comment] 2022-01-18 04:32
Just a heads up, looks like the feature was removed. Presumably there are plans to reimplement, but not certain. Just stumbled onto this support article about it. 

https://help.polyend.com/330743-Can-I-use-the-Media-Transfer-Protocol-MTP-to-copy-files-on-the-SD-card-using-direct-connection-between-the-Tracker-and-my-computer

**Closed** 2023-04-26 14:17 UTC
Labels: bug, bug confirmed
